#!/usr/bin/env python3
"""Run core pipeline with automatic failure diagnostics.

Goal:
- single command for production operators
- no manual troubleshooting steps
- no record removal by default
"""

from __future__ import annotations

import argparse
import datetime as dt
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path
from typing import Any


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run core pipeline and auto-diagnose failures")
    parser.add_argument("--input-json", required=True, help="Source input JSON/JSONL path")
    parser.add_argument("--input-array-key", default=None, help="Optional array key when root is object")
    parser.add_argument(
        "--senzing-env",
        required=True,
        help="Path to setupEnv/shell env script used by local Senzing runtime",
    )
    parser.add_argument("--execution-mode", default="local", choices=["local", "auto", "docker"])
    parser.add_argument("--runtime-dir", default="/mnt/mvp_runtime", help="Runtime directory for runs/projects")
    parser.add_argument("--output-root", default="output", help="Output root for final artifacts")
    parser.add_argument("--output-label", default=None, help="Optional output label")
    parser.add_argument("--license-base64-file", default=None, help="Optional license file path")
    parser.add_argument("--data-source", default="PARTNERS")
    parser.add_argument("--tax-id-type", default="TIN")
    parser.add_argument("--step-timeout-seconds", type=int, default=21600)
    parser.add_argument("--load-threads", type=int, default=1)
    parser.add_argument("--load-fallback-threads", type=int, default=1)
    parser.add_argument(
        "--load-shuffle-primary",
        action="store_true",
        help="Keep shuffle enabled on primary sz_file_loader attempts.",
    )
    parser.add_argument(
        "--load-chunk-size",
        type=int,
        default=50000,
        help="Chunk size for automatic load fallback (default: 50000).",
    )
    parser.add_argument(
        "--disable-load-chunk-fallback",
        action="store_true",
        help="Disable chunked load fallback in run_mvp_pipeline.py.",
    )
    parser.add_argument(
        "--keep-load-chunk-files",
        action="store_true",
        help="Keep temporary JSONL chunk files generated by load chunk fallback.",
    )
    parser.add_argument(
        "--load-batch-size",
        type=int,
        default=100000,
        help="Proactive load batch size passed to run_mvp_pipeline.py (default: 100000).",
    )
    parser.add_argument(
        "--keep-load-batch-files",
        action="store_true",
        help="Keep temporary JSONL files generated for proactive load batches.",
    )
    parser.add_argument(
        "--continue-on-failed-file",
        action="store_true",
        help="Continue with next split file when one load-batch file fails.",
    )
    parser.add_argument(
        "--max-failed-files",
        type=int,
        default=0,
        help="Maximum failed split files allowed before abort (default: 0 = unlimited).",
    )
    parser.add_argument(
        "--load-file-timeout-seconds",
        type=int,
        default=180,
        help="Maximum wall-clock seconds allowed per split file load (default: 180).",
    )
    parser.add_argument("--snapshot-threads", type=int, default=1)
    parser.add_argument("--snapshot-fallback-threads", type=int, default=1)
    parser.add_argument("--disable-stream-export", action="store_true", help="Disable stream export mode")
    parser.add_argument(
        "--disable-large-run-tuning",
        action="store_true",
        help="Disable automatic large-run tuning in run_mvp_pipeline.py",
    )
    parser.add_argument("--with-snapshot", action="store_true", help="Enable snapshot step")
    parser.add_argument("--with-why", action="store_true", help="Enable explain/why step")
    parser.add_argument(
        "--search-dirs",
        default="/mnt,/tmp,.",
        help="Roots used by diagnostics to search loader errors/core dumps",
    )
    parser.add_argument(
        "--diagnostic-output-dir",
        default="output/diagnostics",
        help="Directory for generated diagnostic reports",
    )
    parser.add_argument("--skip-diagnostics-on-success", action="store_true")
    return parser.parse_args()


def run_command(command: list[str], cwd: Path) -> tuple[int, float]:
    started = dt.datetime.now()
    proc = subprocess.run(command, cwd=str(cwd), check=False)
    duration = (dt.datetime.now() - started).total_seconds()
    return proc.returncode, duration


def find_latest_json_report(output_dir: Path) -> Path | None:
    files = sorted(output_dir.glob("runtime_diagnostic_*.json"), key=lambda p: p.stat().st_mtime, reverse=True)
    return files[0] if files else None


def read_json(path: Path) -> dict[str, Any]:
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return {}
    return payload if isinstance(payload, dict) else {}


def preflight(args: argparse.Namespace, mvp_root: Path) -> list[str]:
    issues: list[str] = []
    input_path = Path(args.input_json).expanduser().resolve()
    if not input_path.exists():
        issues.append(f"Input file not found: {input_path}")

    senzing_env = Path(args.senzing_env).expanduser().resolve()
    if not senzing_env.exists():
        issues.append(f"Senzing env script not found: {senzing_env}")

    runtime_dir = Path(args.runtime_dir).expanduser().resolve()
    runtime_dir.mkdir(parents=True, exist_ok=True)
    usage = shutil.disk_usage(runtime_dir)
    free_gb = usage.free / (1024.0**3)
    if free_gb < 4:
        issues.append(f"Low free disk in runtime dir ({free_gb:.2f} GB): {runtime_dir}")

    output_root = Path(args.output_root).expanduser()
    if not output_root.is_absolute():
        output_root = (mvp_root / output_root).resolve()
    output_root.mkdir(parents=True, exist_ok=True)

    return issues


def build_pipeline_command(args: argparse.Namespace, mvp_root: Path) -> list[str]:
    app_root = mvp_root / "app"
    command: list[str] = [
        sys.executable,
        str((app_root / "run_mvp_pipeline.py").resolve()),
        "--input-json",
        str(Path(args.input_json).expanduser().resolve()),
        "--execution-mode",
        args.execution_mode,
        "--senzing-env",
        str(Path(args.senzing_env).expanduser().resolve()),
        "--runtime-dir",
        str(Path(args.runtime_dir).expanduser().resolve()),
        "--keep-runtime-dir",
        "--output-root",
        args.output_root,
        "--data-source",
        args.data_source,
        "--tax-id-type",
        args.tax_id_type,
        "--step-timeout-seconds",
        str(args.step_timeout_seconds),
        "--load-threads",
        str(args.load_threads),
        "--load-fallback-threads",
        str(args.load_fallback_threads),
        "--snapshot-threads",
        str(args.snapshot_threads),
        "--snapshot-fallback-threads",
        str(args.snapshot_fallback_threads),
    ]
    if not args.load_shuffle_primary:
        command.append("--load-no-shuffle-primary")
    if not args.disable_load_chunk_fallback:
        command.append("--enable-load-chunk-fallback")
        if args.load_chunk_size > 0:
            command.extend(["--load-chunk-size", str(args.load_chunk_size)])
        if args.keep_load_chunk_files:
            command.append("--keep-load-chunk-files")
    if args.load_batch_size > 0:
        command.extend(["--load-batch-size", str(args.load_batch_size)])
    if args.keep_load_batch_files:
        command.append("--keep-load-batch-files")
    if args.continue_on_failed_file:
        command.append("--continue-on-failed-file")
    if args.max_failed_files > 0:
        command.extend(["--max-failed-files", str(args.max_failed_files)])
    if args.load_file_timeout_seconds > 0:
        command.extend(["--load-file-timeout-seconds", str(args.load_file_timeout_seconds)])
    if args.disable_large_run_tuning:
        command.append("--disable-large-run-tuning")
    if not args.disable_stream_export:
        command.append("--stream-export")
    if args.with_snapshot:
        command.append("--with-snapshot")
    if args.with_why:
        command.append("--with-why")
    if args.input_array_key:
        command.extend(["--input-array-key", args.input_array_key])
    if args.output_label:
        command.extend(["--output-label", args.output_label])
    if args.license_base64_file:
        command.extend(["--license-base64-file", str(Path(args.license_base64_file).expanduser().resolve())])
    return command


def build_diagnose_command(args: argparse.Namespace, mvp_root: Path) -> list[str]:
    app_root = mvp_root / "app"
    return [
        sys.executable,
        str((app_root / "diagnose_senzing_runtime.py").resolve()),
        "--runtime-dir",
        str(Path(args.runtime_dir).expanduser().resolve()),
        "--search-dirs",
        args.search_dirs,
        "--output-dir",
        args.diagnostic_output_dir,
    ]


def main() -> int:
    args = parse_args()
    mvp_root = Path(__file__).resolve().parent.parent

    issues = preflight(args, mvp_root)
    if issues:
        print("PRECHECK FAILED:")
        for item in issues:
            print(f"- {item}")
        return 2

    pipeline_cmd = build_pipeline_command(args, mvp_root)
    print("Running pipeline command:")
    print(" ".join(pipeline_cmd))
    pipeline_code, pipeline_seconds = run_command(pipeline_cmd, mvp_root)
    print(f"Pipeline exit code: {pipeline_code} (duration: {pipeline_seconds:.1f}s)")

    diag_output_dir = Path(args.diagnostic_output_dir).expanduser()
    if not diag_output_dir.is_absolute():
        diag_output_dir = (mvp_root / diag_output_dir).resolve()
    diag_output_dir.mkdir(parents=True, exist_ok=True)

    should_run_diag = (pipeline_code != 0) or (not args.skip_diagnostics_on_success)
    if not should_run_diag:
        return 0

    diagnose_cmd = build_diagnose_command(args, mvp_root)
    print("Running diagnostics command:")
    print(" ".join(diagnose_cmd))
    diag_code, diag_seconds = run_command(diagnose_cmd, mvp_root)
    print(f"Diagnostics exit code: {diag_code} (duration: {diag_seconds:.1f}s)")

    latest_report = find_latest_json_report(diag_output_dir)
    if latest_report is None:
        print("WARNING: diagnostic JSON report not found.")
        return pipeline_code

    payload = read_json(latest_report)
    summary = payload.get("summary", {}) if isinstance(payload.get("summary"), dict) else {}
    root_causes = payload.get("root_causes", []) if isinstance(payload.get("root_causes"), list) else []
    compact = payload.get("compact_summary_lines", []) if isinstance(payload.get("compact_summary_lines"), list) else []

    print("")
    print("=== AUTO-DIAGNOSTIC SUMMARY ===")
    print(f"Report JSON: {latest_report}")
    print(f"Run dir: {summary.get('run_dir')}")
    print(f"Overall ok: {summary.get('overall_ok')}")
    print(f"Failure step: {summary.get('failure_step')}")
    print(f"Run error: {summary.get('run_error')}")
    if root_causes:
        print("Probable causes:")
        for item in root_causes:
            print(f"- {item}")
    if compact:
        print("")
        print("COPY THIS BLOCK:")
        print("-----8<-----")
        for line in compact:
            print(line)
        print("----->8-----")

    return pipeline_code


if __name__ == "__main__":
    raise SystemExit(main())
